### ISSUE TITLE
TSM default bag slot, item not sending

### ISSUE THREAD

**Issue by intruder0** [Jaliborc/Scrap#44]
Some items have to be moved to other slots in order for TSM to send the item.
Turn off Bagon and item was sent. It seems the default bag (1st bag) has an issue.

**Comment by KyrosKrane** [comment]
The issue is not with the bag; I had the same problem happen with items in other bags. The reason it worked when you turned off Bagnon is that you reloaded your UI, which fixes the TSM issue. You can get the same fix by leaving Bagnon loaded, and just doing a /reload - the sending will work.

I haven't tested whether I can reproduce the problem without Bagnon loaded, so I don't know if it's a TSM issue or a Bagnon issue.

**Comment by KyrosKrane** [comment]
Also, this is the issues list for Scrap, not Bagnon...
